Repository boostcampwm-2024/refactor-and04-Nature-Album, pull requests merged in 2025-01, with the labels that each got.

#1 여러 가지로 나뉘어 있던 TopAppBar 통합
  app/src/main/java/com/and04/naturealbum/ui/add/savephoto/SavePhotoScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/album/labelphotos/AlbumFolderScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/album/labels/AlbumScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/album/photoinfo/PhotoInfo.kt
  app/src/main/java/com/and04/naturealbum/ui/component/TopAppBar.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenPortrait.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/utils/ComposeUtils.kt
  app/src/main/res/values/strings.xml
Labels: Refactoring

#2 Compose Navigation 코드 및 클래스 분리
  app/src/main/java/com/and04/naturealbum/ui/NatureAlbumApp.kt
  app/src/main/java/com/and04/naturealbum/ui/add/labelsearch/navigation/LabelSearchNavigation.kt
  app/src/main/java/com/and04/naturealbum/ui/add/savephoto/navigation/SaveAlbumNavigation.kt
  app/src/main/java/com/and04/naturealbum/ui/album/labelphotos/navigation/AlbumFolderNavigation.kt
  app/src/main/java/com/and04/naturealbum/ui/album/labels/navigation/LabelsAlbumNavigation.kt
  app/src/main/java/com/and04/naturealbum/ui/album/photoinfo/navigation/PhotoInfoNavigation.kt
  app/src/main/java/com/and04/naturealbum/ui/friend/navigation/FriendSearchNavigation.kt
  app/src/main/java/com/and04/naturealbum/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/navigation/MapNavigation.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumNavigator.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NatureAlbumState.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NavHost.kt
Labels: Refactoring

#4 [Refactor] Stability 검사
  app/src/main/java/com/and04/naturealbum/data/localdata/room/Data.kt
  app/src/main/java/com/and04/naturealbum/ui/album/labelphotos/AlbumFolderScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/component/ClippingButton.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenLandscape.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeScreenPortrait.kt
Labels: Refactoring

#3 friend 패키지 변경 및 UserManager 패키지 이동
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
  app/src/main/java/com/and04/naturealbum/di/AuthenticationModule.kt
  app/src/main/java/com/and04/naturealbum/ui/album/labelphotos/AlbumFolderViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/component/TopAppBar.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/friendsearch/FriendSearchScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/mypage/friendsearch/FriendViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/utils/UserManager.kt
Labels: Refactoring

#5 [Fix] friendsearch navigation 패키지 이동
  app/src/main/java/com/and04/naturealbum/ui/mypage/friendsearch/navigation/FriendSearchNavigation.kt
  app/src/main/java/com/and04/naturealbum/ui/navigation/NavHost.kt
Labels: bug

#8 [Refactor] MapView 생명주기 관리 및 리소스 정리 방식 개선
  app/src/main/java/com/and04/naturealbum/data/dto/RoomDataDto.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
Labels: Refactoring

#6 이진 탐색으로 동기화 성능 개선
  app/src/main/java/com/and04/naturealbum/background/workmanager/SearchAlgorithm.kt
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
  app/src/main/java/com/and04/naturealbum/data/dto/FirebaseDto.kt
  app/src/main/java/com/and04/naturealbum/data/dto/RoomDataDto.kt
Labels: Refactoring

#7 LabelSearchScreen UiState 추가 및 안정성을 위한 Ui Test 코드 구현
  app/build.gradle.kts
  app/src/androidTest/java/com/and04/naturealbum/ui/add/labelsearch/LabelSearchTest.kt
  app/src/main/java/com/and04/naturealbum/ui/add/labelsearch/LabelSearchScreen.kt
  app/src/main/java/com/and04/naturealbum/ui/add/labelsearch/LabelSearchUiState.kt
  app/src/main/java/com/and04/naturealbum/ui/add/labelsearch/LabelSearchViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/add/savephoto/ObjectDetectorHelper.kt
  gradle.properties
  gradle/libs.versions.toml
Labels: enhancement, Refactoring

#9 WorkManager 동기화 테스트 코드 추가
  app/build.gradle.kts
  app/src/androidTest/java/com/and04/naturealbum/background/sync/SyncWorkManagerTest.kt
  app/src/main/java/com/and04/naturealbum/data/repository/TestAiRepoImpl.kt
  app/src/main/java/com/and04/naturealbum/data/repository/firebase/TestAlbumRepoImpl.kt
  app/src/main/java/com/and04/naturealbum/data/repository/local/TestLocalDataRepoImpl.kt
  gradle/libs.versions.toml
Labels: enhancement

#11 Local Repository 분리(Album, Label, PhotoDetail, Sync)
  app/src/main/java/com/and04/naturealbum/background/workmanager/SynchronizationWorker.kt
  app/src/main/java/com/and04/naturealbum/data/repository/firebase/AlbumRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/local/LabelRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/local/LocalAlbumRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/local/LocalDataRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/local/PhotoDetailRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/local/SyncRepository.kt
  app/src/main/java/com/and04/naturealbum/data/repository/local/impl/LabelRepositoryImpl.kt
  app/src/main/java/com/and04/naturealbum/data/repository/local/impl/LocalAlbumRepositoryImpl.kt
  app/src/main/java/com/and04/naturealbum/data/repository/local/impl/PhotoDetailRepositoryImpl.kt
  app/src/main/java/com/and04/naturealbum/data/repository/local/impl/SyncRepositoryImpl.kt
  app/src/main/java/com/and04/naturealbum/di/FirebaseModule.kt
  app/src/main/java/com/and04/naturealbum/di/RoomModule.kt
  app/src/main/java/com/and04/naturealbum/ui/add/labelsearch/LabelSearchViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/add/savephoto/SavePhotoViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/album/labelphotos/AlbumFolderViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/album/labels/AlbumViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/album/photoinfo/PhotoInfoViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/home/HomeViewModel.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreenViewModel.kt
Labels: Refactoring

#13 [Refactor] MapScreen 함수로 분리
  app/src/main/java/com/and04/naturealbum/ui/maps/ClusterManager.kt
  app/src/main/java/com/and04/naturealbum/ui/maps/MapScreen.kt
Labels: Refactoring
